# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jordan Newberry
email: jordan.newberry@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a professional Chef turned Software Developer. I spent
  over 10 years working in various fine-dining kitchens around the Twin Cities. After over a decade of dedicated 
  service I realized it just wasn't my passion anymore.
  That realization lead me to the world of programming, where I discovered Prime Digital Academy.
  My time in this program has taken my new found interest in programming and turned it into so much more.
  It has been quite the journey so far. I've been able to meet a lot of like-minded individuals from all kinds
  of backgrounds. I'm having a blast and I can't wait to bring this energy into the work force.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jordannewberry21.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  jordanNewberry21
phone: (615) 456-3055
city: Shoreview
state: MN
linkedin_url: https://www.linkedin.com/in/jordan-newberry-3174a31bb/
github_url: https://github.com/jordanNewberry21
instagram_url: https://www.instagram.com/namesarehard_/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
